name: Specter
version: 2.1.0
author: ["Falkirks", "FaizDev", "ItsToxicGG"]
main: specter\Specter
api: [4.0.0]
softdepend: ["iControlU"]
commands:
  specter:
    usage: /specter <action> <player> [params]
    permission: specter.command
    aliases: ['s']
permissions:
  specter:
    default: op
    children:
      specter.command:
        default: op
